[package]
name = "simple_api"
version = "0.1.0"
edition = "2021"


[dependencies]
actix-web = "4"
regex = "1.11.1"
actix-multipart = "0.7.2"    
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1", features = ["v4"] }
futures-util = "0.3"

